# Generated by Django 3.2.10 on 2021-12-28 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0002_taskshare'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskshare',
            name='request',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='taskshare',
            name='status',
            field=models.CharField(choices=[('Admin', 'Admin'), ('Spectator', 'Spectator')], default=1, max_length=255),
            preserve_default=False,
        ),
    ]
