# Generated by Django 3.2.10 on 2021-12-28 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0003_auto_20211228_1215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskshare',
            name='request',
            field=models.BooleanField(default=False),
        ),
    ]
